### ISSUE TITLE
elementsNoPlain doesn't normalize font sizes properly

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements#166]
The rem sizing of the typography component depends on the rem dimensions being reset from browser defaults, however the code to do this isn't included in elementsNoPlain. @StommePoes has looked into this briefly.

I suppose this is potentially an issue for teams that are trying to do an incremental adoption but need to set the font size on the `html` element to a different value than elements needs. Not sure if that's worth thinking about though.

**Comment by StommePoes** [comment]
It turns out lots of styles are deliberately not in the elementsNoPlain.css: margins and sizes of headings, link colours, etc.

I no longer remember why we have elementsNoPlain, because currently it cannot pass our Elements tests in QA due to certain necessary styles being only in the _html-tags.scss file, which NoPlain deliberately ignores.

We need to know what must be in _html-tags that should not be in NoPlain and yet can still pass our QA tests.

**Comment by parkerpearson** [comment]
We had elementsNoPlain to support use cases where the consumer didn't want the default application of styles to various tags.

**Comment by StommePoes** [comment]
I have the base font size set on the html element on both files BUT lots of other fonty, marginy things won't match still, and that's not possible without simply running the full elements. Close?
