### ISSUE TITLE
cannot add additional class after pe-btn

### ISSUE THREAD

**Issue by bobd9978** [Pearson-Higher-Ed/elements#172]
Picture should say it all. pe-btn styling not applied when additional class is added to element's class attribute.

<img width="619" alt="buttons-css" src="https://cloud.githubusercontent.com/assets/4248341/22955866/96858a96-f2ec-11e6-8c15-d5e440a1a2c1.png">

**Comment by StommePoes** [comment]
This is due to the `|=` selector which either matches perfectly, or matches a starts-with followed by a dash.

should probably just be .pe-btn so we can throw .pe-btn on anything to get default button base on anything, esp since it is no longer paired with .cta or .primary classes to combine button styles, those now have their own specific and complete styling anyway.

**Comment by StommePoes** [comment]
@bobd9978 this is released! Can you confirm it's good on your end?

**Comment by bobd9978** [comment]
This is fixed. We're at 1.5.3 currently.

**Comment by JasonLantz** [comment]
bob says fixed... closing the issue
