### ISSUE TITLE
Button 'disabled' attribute not changing background color

### ISSUE THREAD

**Issue by briandunnpearson** [Pearson-Higher-Ed/elements#34]
The docs say I can add a disabled attribute and 'pe--btn' and 'pe-btn--link' will change the background (or link) color, but that is not happening for me using ReactJs.  I think the .scss is missing an attribute selector for [disabled]... or I'm going crazy.

**Comment by StommePoes** [comment]
Hm, there's CSS for it: .pe-btn:disabled, .pe-btn.pe-btn--disabled (both class and attribute). We don't have one for just :disabled or button:disabled though.

Do you have a test case? I'd love to take a look.

**Comment by briandunnpearson** [comment]
Sorry, but I don't have the test case anymore.  Really, it was an <a> with
'disabled' attribute I added dynamically.  You can delete the issue for now
as I'm using the 'pe-btn--disabled' class instead.

**Comment by StommePoes** [comment]
Ah, that's because a's don't *have* a disabled attribute. Buttons do.
It's one of those things that are in our guidelines that bug me-- showing devs to mix the two elements.

However I think if you check the current section on buttons, you'll see there is a suggestion to add aria-disabled to let AT know the "button" is disabled. For styling, yeah the class would be the only way, since a:disabled would never trigger the CSS.

However if it's a control that can be disabled, I *strongly* urge you to consider using a button instead. They work differently, so users esp those who live on the keyboard, expect different behaviours from them.

Anyway, good that the original problem got solved. cheers
